{
 "title": "GitHub Logs",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Deployment Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "projectId": "linkedlens",
     "queryText": "severity >= DEFAULT\nlogName=\"projects/linkedlens/logs/github-actions-log\"\njsonPayload.message =~ \"^Deployment of Model version\""
    }
   ]
  },
  {
   "title": "Data Pipelines Test",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "projectId": "linkedlens",
     "queryText": "severity >= DEFAULT\nlogName=\"projects/linkedlens/logs/github-actions-log\"\njsonPayload.workflow =~ \"^Data Pipelines Unit Tests*\""
    }
   ]
  },
  {
   "title": "Model Unit Tests Results",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "projectId": "linkedlens",
     "queryText": "severity >= DEFAULT\nlogName=\"projects/linkedlens/logs/github-actions-log\"\njsonPayload.workflow =~ \"^Model Unit Tests\""
    }
   ]
  }
 ]
}