{
 "title": "Model Requests",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Requests Received",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "projectId": "linkedlens",
     "queryText": "severity >= DEFAULT\nresource.type = \"k8s_container\"\nlogName=(\"projects/linkedlens/logs/linkedlens_chat_2\" OR \"projects/linkedlens/logs/linkedlens_chat\")\njsonPayload.message =~ \"^Request Received\"  AND jsonPayload.url = \"http://34.74.67.69:60000/invoke\""
    }
   ]
  },
  {
   "title": "Requests Completed Successfully",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "projectId": "linkedlens",
     "queryText": "severity >= DEFAULT\nresource.type = \"k8s_container\"\nlogName=(\"projects/linkedlens/logs/linkedlens_chat_2\" OR \"projects/linkedlens/logs/linkedlens_chat\")\njsonPayload.message =~ \"^Request Completed\" AND jsonPayload.request_details.url = \"http://34.74.67.69:60000/invoke\" AND jsonPayload.request_details.status_code = 200"
    }
   ]
  },
  {
   "title": "Requests Completed",
   "type": "stat",
   "description": "Status code received other than 200",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "projectId": "linkedlens",
     "queryText": "severity >= DEFAULT\nresource.type = \"k8s_container\"\nlogName=(\"projects/linkedlens/logs/linkedlens_chat_2\" OR \"projects/linkedlens/logs/linkedlens_chat\")\njsonPayload.message =~ \"^Request Completed\" AND jsonPayload.request_details.url = \"http://34.74.67.69:60000/invoke\" AND jsonPayload.request_details.status_code != 200"
    }
   ]
  },
  {
   "title": "Mean Duration for Node Execution",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "projectId": "linkedlens",
     "queryText": "severity >= DEFAULT\nresource.type = \"k8s_container\"\nlogName=(\"projects/linkedlens/logs/linkedlens_chat_2\" OR \"projects/linkedlens/logs/linkedlens_chat\")\njsonPayload.event.event = \"node_executed\""
    }
   ]
  },
  {
   "title": "New panel",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "projectId": "linkedlens",
     "queryText": "severity >= DEFAULT\nresource.type = \"k8s_container\"\nlogName=(\"projects/linkedlens/logs/linkedlens_chat_2\" OR \"projects/linkedlens/logs/linkedlens_chat\")\njsonPayload.event.event = \"node_executed\""
    }
   ]
  }
 ]
}