{
 "title": "Post Deployment Model Evaluation",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Average Metrics",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "projectId": "linkedlens",
     "queryText": "severity >= DEFAULT\nlabels.\"python_logger\"= (\"linkedlens_post_eval_2\" OR \"linkedlens_post_eval_test\" OR \"linkedlens_post_eval\")\njsonPayload.message =~ \"^Post Evaluation metrics summary\""
    }
   ]
  },
  {
   "title": "Average Faithfulness",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "projectId": "linkedlens",
     "queryText": "severity >= DEFAULT\nlabels.\"python_logger\"= (\"linkedlens_post_eval_2\" OR \"linkedlens_post_eval_test\" OR \"linkedlens_post_eval\")\njsonPayload.message =~ \"^Post Evaluation metrics summary\""
    }
   ]
  },
  {
   "title": "Average Response Relevance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "projectId": "linkedlens",
     "queryText": "severity >= DEFAULT\nlabels.\"python_logger\"= (\"linkedlens_post_eval_2\" OR \"linkedlens_post_eval_test\" OR \"linkedlens_post_eval\")\njsonPayload.message =~ \"^Post Evaluation metrics summary\""
    }
   ]
  },
  {
   "title": "Average Retrieval Relevance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "projectId": "linkedlens",
     "queryText": "severity >= DEFAULT\nlabels.\"python_logger\"= (\"linkedlens_post_eval_2\" OR \"linkedlens_post_eval_test\" OR \"linkedlens_post_eval\")\njsonPayload.message =~ \"^Post Evaluation metrics summary\""
    }
   ]
  },
  {
   "title": "Run Metrics",
   "type": "timeseries",
   "description": "Metrics for each run.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "projectId": "linkedlens",
     "queryText": "severity >= DEFAULT\nlabels.\"python_logger\"=\"linkedlens_post_eval_2\" OR labels.\"python_logger\"=\"linkedlens_post_eval_test\" OR labels.\"python_logger\"=\"linkedlens_post_eval\"\njsonPayload.message =~ \"^Eval Entry\""
    }
   ]
  },
  {
   "title": "Run Details",
   "type": "table",
   "description": "To inspect queries for each of the runs, click on the cell.",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "projectId": "linkedlens",
     "queryText": "severity >= DEFAULT\nlabels.\"python_logger\"=\"linkedlens_post_eval_2\" OR labels.\"python_logger\"=\"linkedlens_post_eval_test\" OR labels.\"python_logger\"=\"linkedlens_post_eval\"\njsonPayload.message =~ \"^Post Eval Entry\""
    }
   ]
  }
 ]
}