name: Logging Results
description: Logs workflow results to Cloud Logger
inputs:
  severity:
      description: 'Severity of log'
      required: false
  message:
      description: 'Message to be in log'
      required: true
  workflow_type:
      description: 'Type of workflow which ran'
      required: true
  success:
      description: 'Indicates if workflow succeeded (true/false)'
      required: false

runs:
  using: "composite"
  steps:
      - name: Set up gcloud CLI
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
      
      - name: Install gcloud logging components
        run: |
          gcloud components install logging
        shell: bash
      
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
        shell: bash
        
      
      - name: Logs to Google Cloud Logging
        env:
          SEVERITY: ${{ inputs.severity || 'ERROR' }}
          MESSAGE: ${{ inputs.message || 'Workflow failed' }}
          WORKFLOW_TYPE: ${{ inputs.workflow_type || 'Unit Tests' }}
          SUCCESS: ${{ inputs.success || false }}
          PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}  
        run: |
          echo "COMMIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
          echo "TIMESTAMP=$(date -Iseconds)" >> $GITHUB_ENV
          gcloud logging write github-actions-log \
          --payload-type=json \
          --log-name=github-actions-logs \
          --severity=$SEVERITY \
          --project=$PROJECT_ID \
          "$(jq -n \
              --arg msg "$MESSAGE" \
              --arg time "$TIMESTAMP" \
              --arg tag "$COMMIT_SHA" \
              --arg wrkflw "$WORKFLOW_TYPE" \
              --arg success "$SUCCESS" \
              '{message: $msg, timestamp: $ts, image_tag: $tag, workflow:$wrkflw, success:$success}')"
        shell: bash