apiVersion: v1
kind: Service
metadata:
  name: model-dev-service
  namespace: app
spec:
  type: LoadBalancer
  selector:
    app: model-dev
  ports:
  - protocol: TCP
    port: 60000
    targetPort: 80