apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: model-access-policy
  namespace: app
spec:
  podSelector:
    matchLabels:
      app: model-dev
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: frontend-app
      ports:
        - protocol: TCP
          port: 80