apiVersion: v1
kind: ConfigMap
metadata:
  name: model-config
  namespace: app
data:
  PINECONE_ENVIRONMENT: __PINECONE_ENVIRONMENT__
  GOOGLE_PROJECT_ID: __GCP_PROJECT_ID__
  PROMPT_VERSION_QUERY_ANALYZER: "__PROMPT_VERSION_QUERY_ANALYZER__"
  PROMPT_ID_QUERY_ANALYZER: "__PROMPT_ID_QUERY_ANALYZER__"
  PROMPT_VERSION_FINAL_RESPONSE: "__PROMPT_VERSION_FINAL_RESPONSE__"
  PROMPT_ID_FINAL_RESPONSE: "__PROMPT_ID_FINAL_RESPONSE__"
  LANGSMITH_TRACING: "true"
  LANGSMITH_ENDPOINT: "https://api.smith.langchain.com"
  LANGSMITH_PROJECT: "linkedlens-test"
