name: Setup, Build, Deploy

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  setup-build-deploy-push:
    permissions:
      contents: 'read'
      id-token: 'write'

    name: Setup, Build, Publish, and Deploy Model
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./model-development/src

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{env.GCP_PROJECT_ID}}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{secrets.SERVICE_ACCOUNT}}
      
      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: ${{env.GKE_CLUSTER_NAME}}
          location: ${{env.GCP_REGION}}
      
      - id: 'get-pods'
        run: 'kubectl get pods'

      - name: 'Setup Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud cli'
        run: 'gcloud info'
      
      - name: 'Docker auth'
        run: |-
          gcloud auth configure-docker us-east1-docker.pkg.dev
      
      - name: Build image
        run: |-
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker build . --file ./Dockerfile --tag us-east1-docker.pkg.dev/${{env.GCP_PROJECT_ID}}/${{env.ARTIFACT_REPO}}/model-dev:$GITHUB_SHA
        working-directory: .
      
      - name: Docker push
        run: docker push us-east1-docker.pkg.dev/${{env.GCP_PROJECT_ID}}}/${{env.ARTIFACT_REPO}}/model-dev:$GITHUB_SHA
      
      - name: 'Apply ConfigMap'
        run: kubectl apply -f ../../kubernetes/config.yaml
      
      - name: Deploy
        run: |-
          kubectl apply -f ./kubernetes/deployment.yaml
          kubectl apply -f ./kuberentes/service.yaml
      
      - name: Restart deployment
        run: kubectl rollout restart deployment model-dev-deployment
      
      - name: Status of deployment
        run: | 
          if ! kubectl rollout status deployment model-dev-deployment; then
            exit 1
          else
            echo "Deployment successful"