name: Push DAGs changes to VM and Restart Airflow

on:
  #push:
    # branches:
    #   - main
    #   - dev-data-generation
    # paths:
    #  - "data-generation/**"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: execute remote ssh commands with password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            # Define repo path
            REPO_PATH = "/home/${{ secrets.SERVER_USERNAME }}/mlops/LinedLens"

            if [! -d "$REPO_PATH"]; then
              echo "Repo not found, cloning..."
              cd /home/${{ secrets.SERVER_USERNAME }}/mlops
              git clone https://github.com/jaynanduri/LinkedLens.git
            fi

            cd "$REPO_PATH"

            # #Navigate to repo
            # cd "$(find /home -type d -name "LinkedLens" 2>/dev/null | head -n 1)"

            git pull origin dev-data-generation

            cd data-generation

            #Verifying PWD
            if [-d "./data-generation"]; then
              echo "Correct directory"
            else
              echo "Repository not found. Exiting.."
              exit 1
            fi

            # #Pull latest changes
            # git pull
            # cd ./data-generation

            #Re-write env file

            if [ ! -f .env ]; then
              echo "Creating .env file..."
              cat > .env <<EOF
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_CREDENTIALS_PATH=${{ secrets.DB_CREDENTIALS_PATH }}
            AIRFLOW_UID=${{ secrets.AIRFLOW_UID }}
            MAX_OPEN_AI_REQUEST_PER_MIN=${{ secrets.MAX_REQ_PER_MIN }}
            MAX_OPEN_AI_REQUEST_PER_DAY=${{ secrets.MAX_REQ_PER_DAY }}
            OPEN_ROUTER_BASE_URL=${{ secrets.OPEN_ROUTER_BASE_URL }}
            SMTP_SERVER=${{ secrets.SMTP_SERVER }}
            SMTP_STARTTLS=${{ secrets.SMTP_STARTTLS }}
            SMTP_USER=${{ secrets.SMTP_USER }}
            SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
            SMTP_PORT=${{ secrets.SMTP_PORT }}
            SMTP_EMAIL=${{ secrets.SMTP_EMAIL }}
            SMTP_TIMEOUT=${{ secrets.SMTP_TIMEOUT }}
            SMTP_RETRY_LIMIT=${{ secrets.SMTP_RETRY_LIMIT }}
            SMTP_RECIPIENT_EMAILS=${{ secrets.SMTP_RECIPIENT_EMAILS }}
            EOF
            else
              echo ".env file already exists. Skipping creation."
            fi

            mkdir -p dags/src/credentials

            if [ ! -f dags/src/credentials/linkedlens-firestore-srvc-acc.json ]; then
              echo "Creating linkedlens-firestore-srvc-acc.json.json..."
              echo '${{ secrets.GCP_CREDENTIALS_JSON }}' > dags/src/credentials/linkedlens-firestore-srvc-acc.json
            else
              echo "gcp_credentials.json already exists. Skipping creation."
            fi

            # #Restart Airflow
            # docker-compose down &&
            # docker-compose up -d
