name: Push DAGs changes to VM

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #    - "./data-pipelines/**"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test Network Connection
        run: |
          nslookup 34.136.81.6 || echo "DNS Lookup Failed"
          
      - name: execute remote ssh commands with password
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: 34.136.81.6
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SSH_PORT }}
          debug: true
          script: |
              # Define repo path
              REPO_PATH="$(find /home -type d -name "LinkedLens" 2>/dev/null | head -n 1)"
              echo "Repo path is: $REPO_PATH"
              if [ ! -d "$REPO_PATH" ]; then
                echo "Repo not found, cloning..."
                git clone https://github.com/jaynanduri/LinkedLens.git
                echo "Repo cloned.."
              fi
              REPO_PATH="$(find /home -type d -name "LinkedLens" 2>/dev/null | head -n 1)"
              echo $REPO_PATH
              cd $REPO_PATH
              
  

              echo "Updating code from git.."
              git fetch origin main
              git reset --hard origin/main
              git clean -fd
              git pull origin main
  
              # Rewrite .env file
              echo "Creating/Re-writing .env file"
              cat > .env <<EOF
              OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
              DB_NAME=${{ secrets.DB_NAME }}
              GOOGLE_APPLICATION_CREDENTIALS=$HOME/LinkedLens/credentials/linkedlens-firestore-srvc-acc.json
              GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
              MAX_OPEN_AI_REQUEST_PER_MIN=${{ secrets.MAX_OPEN_AI_REQUEST_PER_MIN }}
              MAX_OPEN_AI_REQUEST_PER_DAY=${{ secrets.MAX_OPEN_AI_REQUEST_PER_DAY }}
              OPEN_ROUTER_BASE_URL=${{ secrets.OPEN_ROUTER_BASE_URL }}
              SMTP_SERVER=${{ secrets.SMTP_SERVER }}
              SMTP_STARTTLS=${{ secrets.SMTP_STARTTLS }}
              SMTP_USER=${{ secrets.SMTP_USER }}
              SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
              SMTP_PORT=${{ secrets.SMTP_PORT }}
              SMTP_EMAIL=${{ secrets.SMTP_EMAIL }}
              SMTP_TIMEOUT=${{ secrets.SMTP_TIMEOUT }}
              SMTP_RETRY_LIMIT=${{ secrets.SMTP_RETRY_LIMIT }}
              SMTP_RECIPIENT_EMAILS=${{ secrets.SMTP_RECIPIENT_EMAILS }}
              AIRFLOW_WWW_USER_USERNAME=${{ secrets.AIRFLOW_WWW_USER_USERNAME }}
              AIRFLOW_WWW_USER_PASSWORD=${{ secrets.AIRFLOW_WWW_USER_PASSWORD }}
              EOF
              echo ".env file created"

              #Verifying PWD
              if [ -d "./data-pipelines/data-generation" ]; then
                echo "Correct directory"
              else
                echo "Repository not found. Exiting.."
                exit 1
              fi

              echo "Current directory: $(pwd)"
              mkdir -p credentials
          
              echo "Creating/Re-writing linkedlens-firestore-srvc-acc.json..."
              echo '${{ secrets.GCP_CREDENTIALS_JSON }}' > ./credentials/linkedlens-firestore-srvc-acc.json
              
              # Set airflow UID
              AIRFLOW_UID=$(id -u)
              export AIRFLOW_UID=$AIRFLOW_UID
              echo "AIRFLOW_UID set to $AIRFLOW_UID"
